vote/polls/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib import admin
from django.urls import include, path
admin.autodiscover()

urlpatterns = [
    path('vote/', include('vote.urls')),
    path('admin/', admin.site.urls),
]

vote/vote/urls.py
from django.urls import path

from . import views

app_name = 'vote'
urlpatterns = [
     # ex: /polls/
     path('', views.IndexView.as_view(), name='index'),
     # ex: /polls/5/
     path('<int:pk>/', views.DetailView.as_view(), name='detail'),
     # ex: /polls/5/results/
     path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
     # ex: /polls/5/vote/
     path('<int:question_id>/vote/', views.vote, name='vote'),
]

vote/vote/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
     question_text = models.CharField(max_length=200)
     pub_date = models.DateTimeField('date published')

     def __str__(self):
          return self.question_text

     def was_published_recently(self):
          now = timezone.now()
          return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
     # return now - datetime.timedelta(days=1) <= self.pub_date <= now
     was_published_recently.admin_order_field = 'pub_date'
     was_published_recently.boolean = True
     was_published_recently.short_description = 'published recently?'

class Choice(models.Model):
     question = models.ForeignKey(Question, on_delete=models.CASCADE)
     choice_text = models.CharField(max_length=200)
     votes = models.IntegerField(default=0)

     def __str__(self):
          return self.choice_text

vote/vote/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

# Create your views here.

from .models import Question, Choice

class IndexView(generic.ListView):
    template_name = 'vote/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
	model = Question
	template_name = 'vote/detail.html'
	def get_queryset(self):
		"""
		exclude any questions that aren't published yet.
		"""
		return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
	model = Question
	template_name = 'vote/results.html'

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (keyError, Choice.DoesNotExist):
		# Redisplay the question voting form.
		return render(request, 'vote/detail.html', {
			'question': question,
			'error_message': "you didn't select a choice.",
		})
	else:
		selected_choice_votes +=1
		selected_choice.save()
		return HttpResponseRedirect(reverse('vote:results', args=(question.id,)))

# def detail(request, question_id):
	# question = get_object_or_404(Question, pk=question_id)
	# return render(request, 'vote/detail.html', {'question': question})

""" def results(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	return render(request, 'vote/results.html', {'question': question}) """

def vote(request, question_id):
	return HttpResponse("you are voting on question %s." % question_id)

from .models import Question

vote/vote/templates/vote/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %} <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'vote:vote' question.id %}" method="post">
     {% csrf_token %}<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"><label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
     <input type="submit" value="Vote"></form>
<ul>
     {% for choice in question.choice_set.all %}
     <li>{{ choice.choice_text }}</li>
     {% endfor %}
</ul>

vote/vote/templates/vote/index.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <meta http-equiv="X-UA-Compatible" content="ie=edge">
     <title>tonylee vote app</title>
     {% load static %}
<link rel="stylesheet" href="{% static 'vote/style.css'">

</head>
<body>

{% if latest_question_list %}
     <ul>
          {% for question in latest_question_list %}
          <li><a href="{% url 'vote:detail' question.id %}">{{ question.question_text }}</a></li>
          {% endfor %}
     </ul>
{% else %}
     <p>No polls are available.</p>
{% endif %}

     
</body>
</html>

vote/vote/templates/vote/results.html
<h1>{{ question.question_text}}</h1>

<ul>
     {% for choice in question.choice_set.all %}
     <li>{{ choice.choice_text }} -- {{ choice.votes }}</li>
     {% endfor %}
</ul>
<a href="{% url 'vote:detail' question.id %}">Vote again?</a>